### ISSUE TITLE
WebRTC Vulnerability

### ISSUE THREAD

**Issue by iamrohanbro** [n8fr8/orbot#138]
Dev can you please look into this? https://beebom.com/vpn-leak-ip-address-webrtc-bug/
I'm not sure whether our VPN its patched against it, there a link under this where I can check whether my browser+VPN setup is vulnerable, but I was unsuccessful in conducting the test properly.
The description at the link clearly mentions that browsers using TOR VPN are affected.
Thank you.

**Comment by n8fr8** [comment]
Orfox browser is not vulnerable to this. It is safe to use. If you want to browse the web through Tor on your phone, and want the best chance of anonymity, use Orfox, and no other browser. You don't need the VPN activated for Orfox.

Orbot itself as a VPN proxy, only routes TCP traffic and not UDP traffic. However, I want to point out that, any apps you use can easily get your real IP and other personal info, since they are apps running on your phone or device. Orbot's VPN is to stop networks from censorship or blocking your apps, not to protect you from apps themselves.

**Comment by iamrohanbro** [comment]
OK, thank you for your time.
